export default {
   getWorkBooksAndFolders: 'folders/',
   getSharedWorkBooksAndFolders: 'shared_workbooks_folders/v1/',
   pinnedWorkbooksAndStarredFolders: 'pinned_workbooks_starred_folders/v1/',
   createWorkbook: 'workbooks/v1/',
   createFolder: 'folders/v1/',
   getSearchFoldersAndWorkbooks: 'search_workbooks_folders/v1/',
   rootFolderDetails: 'root_folder/v1/',
   workbook: 'workbook/',
   folder: 'folder/',
   getRolesData: 'roles/',
   shareFolder: 'folders/share/',
   shareWorkbook: 'workbooks/share/',
   workbooks: 'workbooks/',
   moveFolder: 'move_folder/v1/',
   moveWorkbook: 'move_workbook/v1/',
   folders: 'folders/',
   trashFoldersAndWorkbooks: 'trash/folders_and_workbooks/v1/',
   sharedFolderDetails: 'shared_folder_details/v1/',
   getParentFolderId: 'get/parent/folder/v1/',
   emptyTrash: '/trash/v1/',
   publishWorkbooks: 'get_published_workbooks/',
   assignments: '/assignment_workbooks/v1/',
   learnings: '/learning_workbooks/v1/',
   userProjects: '/user_projects/v1/'
}
